


const SET_USER = 'SET_USER'
const DELETE_USER = 'DELETE_USER'

const EDIT_COMMENT = 'EDIT_COMMENT'
const DELETE_COMMENT = 'DELETE_COMMENT'

export {SET_USER,DELETE_USER,EDIT_COMMENT,DELETE_COMMENT}